# Generated by Django 5.2.11 on 2026-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Df', 'Draft'), ('PB', 'PUBLISHED')], default='Df', max_length=2),
        ),
    ]
